//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comdis.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Comdis.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Label_Bank {
            get {
                return ResourceManager.GetString("Label_Bank", resourceCulture);
            }
        }
        
        public static string Label_2Decimals {
            get {
                return ResourceManager.GetString("Label_2Decimals", resourceCulture);
            }
        }
        
        public static string Label_SOITitle {
            get {
                return ResourceManager.GetString("Label_SOITitle", resourceCulture);
            }
        }
        
        public static string Labe_Add {
            get {
                return ResourceManager.GetString("Labe_Add", resourceCulture);
            }
        }
        
        public static string Label_Save {
            get {
                return ResourceManager.GetString("Label_Save", resourceCulture);
            }
        }
        
        public static string Label_Print {
            get {
                return ResourceManager.GetString("Label_Print", resourceCulture);
            }
        }
        
        public static string Label_Close {
            get {
                return ResourceManager.GetString("Label_Close", resourceCulture);
            }
        }
        
        public static string Label_ModalAdd {
            get {
                return ResourceManager.GetString("Label_ModalAdd", resourceCulture);
            }
        }
        
        public static string Msg_notAvailableItems {
            get {
                return ResourceManager.GetString("Msg_notAvailableItems", resourceCulture);
            }
        }
        
        public static string Msg_searchDictionary {
            get {
                return ResourceManager.GetString("Msg_searchDictionary", resourceCulture);
            }
        }
        
        public static string Label_Product {
            get {
                return ResourceManager.GetString("Label_Product", resourceCulture);
            }
        }
        
        public static string Label_Quantity {
            get {
                return ResourceManager.GetString("Label_Quantity", resourceCulture);
            }
        }
        
        public static string Label_Price {
            get {
                return ResourceManager.GetString("Label_Price", resourceCulture);
            }
        }
        
        public static string Label_subtotal {
            get {
                return ResourceManager.GetString("Label_subtotal", resourceCulture);
            }
        }
        
        public static string Label_edit {
            get {
                return ResourceManager.GetString("Label_edit", resourceCulture);
            }
        }
        
        public static string Label_delete {
            get {
                return ResourceManager.GetString("Label_delete", resourceCulture);
            }
        }
        
        public static string Msg_addedItem {
            get {
                return ResourceManager.GetString("Msg_addedItem", resourceCulture);
            }
        }
        
        public static string Label_Created {
            get {
                return ResourceManager.GetString("Label_Created", resourceCulture);
            }
        }
        
        public static string Label_CreatedBy {
            get {
                return ResourceManager.GetString("Label_CreatedBy", resourceCulture);
            }
        }
        
        public static string Label_Updated {
            get {
                return ResourceManager.GetString("Label_Updated", resourceCulture);
            }
        }
        
        public static string Label_UpdatedBy {
            get {
                return ResourceManager.GetString("Label_UpdatedBy", resourceCulture);
            }
        }
        
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        public static string Label_Adress {
            get {
                return ResourceManager.GetString("Label_Adress", resourceCulture);
            }
        }
        
        public static string Label_Adress2 {
            get {
                return ResourceManager.GetString("Label_Adress2", resourceCulture);
            }
        }
        
        public static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        public static string Label_Phone2 {
            get {
                return ResourceManager.GetString("Label_Phone2", resourceCulture);
            }
        }
        
        public static string Label_RFC {
            get {
                return ResourceManager.GetString("Label_RFC", resourceCulture);
            }
        }
        
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        public static string Label_UOM {
            get {
                return ResourceManager.GetString("Label_UOM", resourceCulture);
            }
        }
        
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        public static string Label_Code {
            get {
                return ResourceManager.GetString("Label_Code", resourceCulture);
            }
        }
        
        public static string Label_BankAccount {
            get {
                return ResourceManager.GetString("Label_BankAccount", resourceCulture);
            }
        }
        
        public static string Label_Customer {
            get {
                return ResourceManager.GetString("Label_Customer", resourceCulture);
            }
        }
        
        public static string Label_RequestedDeliveryDate {
            get {
                return ResourceManager.GetString("Label_RequestedDeliveryDate", resourceCulture);
            }
        }
        
        public static string Label_DeliveryAdress {
            get {
                return ResourceManager.GetString("Label_DeliveryAdress", resourceCulture);
            }
        }
        
        public static string Label_Comments {
            get {
                return ResourceManager.GetString("Label_Comments", resourceCulture);
            }
        }
        
        public static string Label_Discount1 {
            get {
                return ResourceManager.GetString("Label_Discount1", resourceCulture);
            }
        }
        
        public static string Label_Discount2 {
            get {
                return ResourceManager.GetString("Label_Discount2", resourceCulture);
            }
        }
        
        public static string Label_Discount3 {
            get {
                return ResourceManager.GetString("Label_Discount3", resourceCulture);
            }
        }
        
        public static string MSG_ErrorCreating {
            get {
                return ResourceManager.GetString("MSG_ErrorCreating", resourceCulture);
            }
        }
        
        public static string MSG_ErrorEditar {
            get {
                return ResourceManager.GetString("MSG_ErrorEditar", resourceCulture);
            }
        }
        
        public static string MSG_EditedITem {
            get {
                return ResourceManager.GetString("MSG_EditedITem", resourceCulture);
            }
        }
        
        public static string MSG_RequieredProduct {
            get {
                return ResourceManager.GetString("MSG_RequieredProduct", resourceCulture);
            }
        }
        
        public static string MSG_DeletedItem {
            get {
                return ResourceManager.GetString("MSG_DeletedItem", resourceCulture);
            }
        }
        
        public static string MSG_DeleteQuestion {
            get {
                return ResourceManager.GetString("MSG_DeleteQuestion", resourceCulture);
            }
        }
        
        public static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
        
        public static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        public static string MSG_DidSave {
            get {
                return ResourceManager.GetString("MSG_DidSave", resourceCulture);
            }
        }
        
        public static string Label_CustomerInformation {
            get {
                return ResourceManager.GetString("Label_CustomerInformation", resourceCulture);
            }
        }
        
        public static string Label_OrderTotals {
            get {
                return ResourceManager.GetString("Label_OrderTotals", resourceCulture);
            }
        }
        
        public static string Label_tax {
            get {
                return ResourceManager.GetString("Label_tax", resourceCulture);
            }
        }
        
        public static string Label_Total {
            get {
                return ResourceManager.GetString("Label_Total", resourceCulture);
            }
        }
        
        public static string Label_salesDetail {
            get {
                return ResourceManager.GetString("Label_salesDetail", resourceCulture);
            }
        }
        
        public static string Label_Sales {
            get {
                return ResourceManager.GetString("Label_Sales", resourceCulture);
            }
        }
        
        public static string Label_new {
            get {
                return ResourceManager.GetString("Label_new", resourceCulture);
            }
        }
        
        public static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        public static string Label_DateTo {
            get {
                return ResourceManager.GetString("Label_DateTo", resourceCulture);
            }
        }
        
        public static string Label_DateFrom {
            get {
                return ResourceManager.GetString("Label_DateFrom", resourceCulture);
            }
        }
        
        public static string Label_SalesNumber {
            get {
                return ResourceManager.GetString("Label_SalesNumber", resourceCulture);
            }
        }
        
        public static string Label_Sale {
            get {
                return ResourceManager.GetString("Label_Sale", resourceCulture);
            }
        }
        
        public static string Label_NewA {
            get {
                return ResourceManager.GetString("Label_NewA", resourceCulture);
            }
        }
        
        public static string Label_Create {
            get {
                return ResourceManager.GetString("Label_Create", resourceCulture);
            }
        }
    }
}
